### ISSUE TITLE
Crash whilst trying to access firefox cache?

### ISSUE THREAD

**Issue by KNejad** [wurstmeister/zookeeper-docker#21]
I'm not sure how this happened or why this would happen but whilst running the docker compose to install kafka-docker it fetches zookeeper and then crashes whilst trying to read my Firefox cache. Here are the relevant lines:

```
Digest: sha256:7a7fd44a72104bfbd24a77844bad5fabc86485b036f988ea927d1780782a6680
Status: Downloaded newer image for wurstmeister/zookeeper:latest
Building kafka
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.24.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 127, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 1085, in up
    to_attach = up(False)
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 1081, in up
    silent=options.get('--quiet-pull'),
  File "/usr/lib/python3.7/site-packages/compose/project.py", line 527, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent)
  File "/usr/lib/python3.7/site-packages/compose/service.py", line 360, in ensure_image_exists
    self.build()
  File "/usr/lib/python3.7/site-packages/compose/service.py", line 1084, in build
    platform=self.platform,
  File "/usr/lib/python3.7/site-packages/docker/api/build.py", line 160, in build
    path, exclude=exclude, dockerfile=dockerfile, gzip=gzip
  File "/usr/lib/python3.7/site-packages/docker/utils/build.py", line 31, in tar
    root=root, fileobj=fileobj, gzip=gzip, extra_files=extra_files
  File "/usr/lib/python3.7/site-packages/docker/utils/build.py", line 79, in create_archive
    i = t.gettarinfo(full_path, arcname=path)
  File "/usr/lib/python3.7/tarfile.py", line 1807, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/home/keeyan/.cache/mozilla/firefox/m5oamn5b.default-release/cache2/entries/CFEF76D7EA8BC3B58AB166E38AE1F5FAEA823492'
```

This is probably unrelated to this repo but I figured it was worth mentioning in case there is something wrong going on here. Although most likely I just don't realise how something was working and this is reasonable (maybe it was parsing my home directory for some reason and the cache file just got deleted?).

The exact command I ran was `sudo docker-compose -f docker-compose.yml up -d` where `docker-compose.yml` was received from https://raw.githubusercontent.com/wurstmeister/kafka-docker/master/docker-compose.yml

*Edit:* After running it again it crashes at a different file in my home directory

**Comment by KNejad** [comment]
I'm being stupid. It's just docker looking for the Dockerfile so it's scanning the whole directory starting from `~/`
